- hosts: 3.22.186.166
  become: true
  tasks:
    - name: create new Deployment
      command: kubectl apply -f Deployment.yaml
    - name: create new servie
      command: kubectl apply -f Service.yaml