- hosts: 3.134.78.64
  become: true
  tasks:
    - name: create new Deployment
      command: kubectl apply -f /home/ubuntu/Deployment.yaml
    - name: create new servie
      command: kubectl apply -f /home/ubuntu/Service.yaml
  