apiVersion: v1
kind: Service
metadata:
  name: miss-simran
  labels:
    app: miss-simran
spec:
  ports:
    - port: 8083
      targetPort: 80
      nodePort: 32100
  selector:
    app: miss-simran
  type: LoadBalancer